Added threshold

diff --git a/.github/workflows/audit.yml b/.github/workflows/audit.yml
--- a/.github/workflows/audit.yml
+++ b/.github/workflows/audit.yml
@@ -21,9 +21,6 @@ jobs:
     - name: Verify Dependencies
       run: go mod verify    
 
-    - name: Build
-      run: go build -v ./...  
-
     - name: Run go vet
       run: go vet ./...  
 
@@ -41,3 +38,27 @@ jobs:
 
     - name: Run tests
       run: go test -race -vet=off ./...  
+
+    - name: Unit tests
+      run: | 
+            go test ./... -coverprofile coverage.out -covermode count
+            go tool cover -func covergae.out   
+
+    - name: Covergae Gate 
+      env:
+          COVERAGE_THRESHOLD: 65
+      run: |
+            echo "Checking if the coverage is about the threshold or not"
+            echo "Current Threshold : $COVERAGE_THERSHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
+            
+    - name: Build
+      run: go build -o dockerhub-go
